### ISSUE TITLE
error HardwareSerial for tiny 2313 

### ISSUE THREAD

**Issue by lestofante** [TCWORLD/ATTinyCore#16]
tryng to compile some code for attiny 2313 a friend of mine has error:

C:..\tiny_TCW_2.0_prove4313\cores\tiny\HardwareSerial.cpp: In function 'void __vector_8()':
C:..\tiny_TCW_2.0_prove4313\cores\tiny\HardwareSerial.cpp:192:12: error: lvalue required as left operand of assignment

line seems to be "UDR0 = c;" but this tiny should use "UDR"

**Comment by lestofante** [comment]
Leonardo Miliani modified HardwareSerial to be compilable, and also updated the code to be compatible with newest avr-gcc. Testing is going on, code can be found here
http://forum.arduino.cc/index.php?topic=202624.msg1659251#msg1659251

**Comment by TCWORLD** [comment]
I'll update this at some point. 
That link isn't much use to me as English is the only language I speak.

To be honest with an Attiny2313 or any Attiny2x you are better off ditching much of the Arduino stuff, especially digitalxxx and analogxxx and instead use direct register writes. Using the TinyNoMillis() core would also be advantageous. There is so little flash available with these devices it is better to write less generic and more optimised code.

**Comment by MauroMombelli** [comment]
the link is to a post with cointains a .zip file with the modificed sources.
I'm not tryng todo the mod, i'm just reporting the work done by others, that have their own motivation :)

**Comment by lestofante** [comment]
the linked files also add tiny4313 compatibility

**Comment by TCWORLD** [comment]
Part of this turned out to be caused by an unintentional regression of changed - copy and paste is dangerous! I have put the changes back and updated the file to use the proper ISR() routines instead of the deprecated SIGNAL() ones. If you have any issues still, reopen and I will have a look.
I have been incredibly busy at University so have not been able to look into the problem until now.
