### ISSUE TITLE
Pins addressed using Arduino pin # instead of chip pin #

### ISSUE THREAD

**Issue by mwoodsmall** [TCWORLD/ATTinyCore#18]
I am new to this chip, but this seems like a strange way of doing things and I believe this diverges from the way other attiny cores do this.

Admittedly, I could be doing something wrong.  I am using the ATTiny84, and Using this pin mapping from https://github.com/TCWORLD/ATTinyCore/blob/master/tiny/variants/tinyX4/pins_arduino.h

I was expecting the following code to work by addressing the chip pin (would have been 13), but instead I had to reference pin 10.

int led = 10;

// the setup r1utine runs once when you press reset:
void setup() {  
  // initialize the digital pin as an output.
  pinMode(led, OUTPUT);  
}

// the loop routine runs over and over again forever:
void loop() {
  digitalWrite(led, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);               // wait for a second
  digitalWrite(led, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);               // wait for a second
}

Like I said, there is a good chance that I am missing something, but this seemed off.

**Comment by TCWORLD** [comment]
For one it is not possible to do it entirely by pin number - e.g. where would digital pin 0 be, and digital pin 1 for that matter.
Secondly, I didn't choose the mapping, my mappings stay consistent with the Arduino-tiny core from which this branched off.

**Comment by mwoodsmall** [comment]
That makes sense.  What was throwing me off was when I was running the arduino-tiny core that this was branched off of, I had it set to (chip) pin 13 and I was getting around 1.5 volts off of it (expecting 5).  I thought it had something to do with the library so I switched to this one.  Turns out I shouldn't have been getting any voltage off of pin 13 from the get go and something funky was happening.  Anyways, thanks for clearing this up and sorry for opening an extraneous issue.

**Comment by techydude** [comment]
Michael,
forgive me if i'm covering old ground for you.
(1) if a pin is set to input, and there's no pull-up (or -down) resistor (external, or turned on in the chip) then with a high impedance 'scope or DMM you will see 'random' voltages between 0..Vcc.
(2) a small part of what 'Arduino' is, is an abstraction of the hardware, across a range of Atmel AVR chips, and now several others (e.g. Freescale Kinetis K20 family as used on the Teensy 3.x boards).  Virtually every microcontroller (regardless of brand) presents, for example, "Port A" GPIO pins on different (chip) pin numbers, depending on the chip's package type (i.e. DIP, SO, QFN, etc).  One package with a relatively limited number of pins (ie. 28-pin DIP of the ATmega328 on the Uno) will 'multiplex' basic GPIO pins with special-function pins for UARTs, SPI, I2C, PWM, ADC, etc, which significantly limits how much you can do, whereas others spread out the allocation of GPIOs & special-function pins so that you not only get most of the special-function pins, but also most of the GPIO pins (e.g. ATmega2560 on the 'Arduino Mega'), without having to choose one or the other.  The key here is that there are literally _hundreds_ of microcontroller variants, even just within the Atmel range, because of this.
Arduino hides this by offering a specific set of developments boards with specific choices of microcontrollers, and then allocates GPIO pins and special-function i/o pins accordingly, so that "Pin 3" in your Arduino sketch always wiggles the pin labelled "Pin 3" on the Arduino's Shield stacking pin-headers.  
But when you go beyond the Arduino 'spec'/range of boards, you're kinda on your own; so, for example, the 'Arduino-tiny' core from which this library is branched chose a handful of the ATtiny chips and said "OK, lets make "Arduino Pin 0" be chip-pin-3 on ATtinyX, and chip-pin-11 on ATtinyY, and chip-pin-8 on ATtinyZ", all within the limits imposed by the function-to-pin multiplexing specific to each of those many ATtiny chips.
Also, to ease programming SNAFUs by neophytes, Arduino sketches count i/o pins from 0 and up, whereas as TC said above, there's never a 'pin 0' on any chip, there's just "Port-A pins 0..7" (or 0..15 or 0..31 depending on the width of the databus), then Port-B pins 0..7, and so on, all mapped pretty much arbitrarily to chip-pins.

**Comment by mwoodsmall** [comment]
Thanks for the thorough explanation.  I am just getting into the hardware game so most of that was all new information to me.  Thanks again!
