### ISSUE TITLE
Optiboot Makefile incorrect for ATtiny84 target

### ISSUE THREAD

**Issue by digitalmisery** [TCWORLD/ATTinyCore#4]
I noticed two issues when using your Optiboot Makefile to make and flash bootloader code for the ATtiny84. I am specifically using an ATTiny84 at 8MHz.  This issue may also be applicable to other chip variants and/or frequencies.
1. The fuse bits are incorrect for LFUSE and HFUSE. They seem to be transposed.  They should be as in your [boards.txt](https://github.com/TCWORLD/ATTinyCore/blob/master/tiny/boards.txt) file:
   - LFUSE = E2
   - HFUSE = D7
   - EFUSE = FE
2. The lock bits used in the makefile (0x3f and 0x2f) are not recognized by AVRDUDE for the ATtiny84 since it only has 2 lock bits (0 and 1 - see Table 19-1 in the [datasheet](http://www.atmel.com/Images/doc8183.pdf)). For other targets like the ATmega328, the lock bits in the makefile make sense because it has 6 lock bits.

Once I fixed those issues, I was able to successfully make the firmware using "make attiny84" and flash the device and set the fuses with "make attiny84_isp". I attempted to use the tinytuner code but it did not seem to be set properly for the ATtiny84 either.  I'll have to figure out what's going on there and submit a separate issue.  Basically the instructions say to connect via software serial at 9600 baud and type "x" but it looks like it starts up at 19200 baud. My default oscillator values must have been OK since I didn't have any issue loading code from the Arduino IDE (1.0.3) when using the non-tuned Optiboot.

Thanks for your great software! It's fun being able to use ATtinys like their big brothers.

**Comment by TCWORLD** [comment]
Ahh, right, I'm not sure I had properly set the fuses and things in the makefile as I use arduino to burn the bootloader which uses numbers from the boards.txt file.
If you want to upload a corrected version of the makefile, I would be happy to pull it into the repository.

There is a glitch in the tinytuner code that I found a few days ago. It doesn't stop it working, it just means that things that are printed out are garbage (because they are sent at 19200baud as you determined). If you send the letter 'x' slowly at 9600 baud and keep going until the status led stops blinking when you send characters, then tuning will work.
I will upload a corrected version of the optiboot code asap.

Thanks,
Tom
